### ISSUE TITLE
装了ffmpeg 重启了电脑还是不能发送语音

### ISSUE THREAD

**Issue by thankU-ubi** [A-kirami/nonebot-plugin-alipayvoice#7]
![image](https://user-images.githubusercontent.com/104612463/186726803-768b182f-2ccf-456a-8cae-b30a0fe4af23.png)

gohttp日志：
08-26 00:55:20 [INFO] nonebot_plugin_gocqhttp | [2821521344] 收到群 测试群(1006443456) 内 THANKU.UB(609638635) 的消息: /支付宝到账 1000元 (-868623838)

noneBOT日志
08-26 00:55:20 [SUCCESS] nonebot | ONEBOT V11 2821521344 | [message.group.normal]: Message -868623838 from 609638635@[群:1006443456] "/支付宝到账 1000元"
08-26 00:55:20 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_alipayvoice, type=message, priority=1, temp=False>
08-26 00:55:20 [WARNING] nonebot_plugin_gocqhttp | [2821521344] 转换CQ码 ({"type": "record", "data": {"file": "https://mm.cqu.cc/share/zhifubaodaozhang/mp3/1000.mp3", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exit status 1 将忽略本段CQ码.
08-26 00:55:20 [WARNING] nonebot_plugin_gocqhttp | [2821521344] 群消息发送失败: 消息为空.
08-26 00:55:20 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_alipayvoice, type=message, priority=1, temp=False> running complete
08-26 00:55:20 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_alipayvoice, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_alipayvoice\__init__.py", line 22, in alipay
    await matcher.send(MessageSegment.record(url))
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 453, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='1', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

**Comment by A-kirami** [comment]
请确保网络环境正常
