### ISSUE TITLE
[BUG]: 发送命令后没反应，控制台报错

### ISSUE THREAD

**Issue by Broken-Deer** [A-kirami/nonebot-plugin-alipayvoice#8]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

nonebot==2.0.0b1

### 问题描述

当我启动插件后，群里说“支付宝到账”时，控制台报错
![image](https://user-images.githubusercontent.com/64290747/194203390-3c556037-5742-4b17-8fad-e1fee922fcc4.png)

完整日志：

```
10-06 10:48:52 [INFO] nonebot_plugin_gocqhttp | [3544086963] 网络诊断完成. 未发现问题
10-06 10:52:08 [INFO] nonebot_plugin_gocqhttp | [3544086963] 收到群 骚话测试专用(805902339) 内 Broken_Deer(3472054691) 的消息: 支付宝到账 (-933727923)
10-06 10:52:08 [SUCCESS] nonebot | ONEBOT V11 3544086963 | [message]: {'time': 1665024727, 'self_id': 3544086963, 'post_type': 'message', 'group_id': 805902339, 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Broken_Deer', 'role': 'owner', 'sex': 'unknown', 'title': '', 'user_id': 3472054691}, 'anonymous': None, 'user_id': 3472054691, 'message_seq': 1269, 'message_type': 'group', 'sub_type': 'normal', 'message_id': -933727923, 'raw_message': '支付宝
到账', 'font': 0, 'message': [{'type': 'text', 'data': {'text': '支付宝到账'}}]}
10-06 10:52:08 [WARNING] nonebot | Error while parsing command for event
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 194, in handle_event
    await handle_event(self, event)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 307, in handle_event
    TrieRule.get_value(bot, event, state)
  File "D:\Python\lib\site-packages\nonebot\rule.py", line 189, in get_value
    message = event.get_message()
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 49, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
10-06 10:52:08 [ERROR] nonebot | Rule check failed for <Matcher from nonebot_plugin_gocqhttp.plugin, type=message, priority=1, temp=False>.
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    if not await Matcher.check_perm(
  File "D:\Python\lib\site-packages\nonebot\matcher.py", line 311, in check_perm
    return event_type == (cls.type or event_type) and await cls.permission(
  File "D:\Python\lib\site-packages\nonebot\permission.py", line 111, in __call__
    results = await asyncio.gather(
  File "D:\Python\lib\site-packages\nonebot\permission.py", line 31, in _run_coro_with_catch
    return await coro
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 76, in __call__
    return await self.call(**values)
  File "D:\Python\lib\site-packages\nonebot\permission.py", line 210, in __call__
    f"{bot.adapter.get_name().split(maxsplit=1)[0].lower()}:{event.get_user_id()}"
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 53, in get_user_id
    raise ValueError("Event has no context!")
ValueError: Event has no context!
10-06 10:52:08 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.nonebot_plugin_cute_message, type=message, priority=30, temp=False>.
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 144, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "D:\Python\lib\site-packages\nonebot\matcher.py", line 340, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "D:\Python\lib\site-packages\nonebot\rule.py", line 144, in __call__
    results = await asyncio.gather(
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 76, in __call__
    return await self.call(**values)
  File "E:\Desktop\bot\smart-driver\.\src\plugins\nonebot_plugin_cute_message\__init__.py", line 40, in _can_reply
    input_message = event.get_plaintext()
  File "D:\Python\lib\site-packages\nonebot\adapters\_event.py", line 124, in get_plaintext
    return self.get_message().extract_plain_text()
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 49, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
10-06 10:52:09 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.nonebot_plugin_jrrp, type=message, priority=60, temp=False>.
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 144, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "D:\Python\lib\site-packages\nonebot\matcher.py", line 340, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "D:\Python\lib\site-packages\nonebot\rule.py", line 144, in __call__
    results = await asyncio.gather(
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 73, in __call__
    values = await self.solve(**kwargs)
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 180, in solve
    value = await field_info._solve(**params)
  File "D:\Python\lib\site-packages\nonebot\params.py", line 158, in _solve
    solved = await task
  File "D:\Python\lib\site-packages\nonebot\params.py", line 266, in _event_plain_text
    return event.get_plaintext()
  File "D:\Python\lib\site-packages\nonebot\adapters\_event.py", line 124, in get_plaintext
    return self.get_message().extract_plain_text()
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 49, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
```

### 重现步骤

1. 安装nb-cli
2. 安装插件
3. 启动nonebot
4. 群里说“支付宝到账”

### 预期行为

按照README说的那样，bot会回复一个语音

### 实际行为

bot什么也没有回复，且抛出错误

### 日志信息

```
10-06 10:48:52 [INFO] nonebot_plugin_gocqhttp | [3544086963] 网络诊断完成. 未发现问题
10-06 10:52:08 [INFO] nonebot_plugin_gocqhttp | [3544086963] 收到群 骚话测试专用(805902339) 内 Broken_Deer(3472054691) 的消息: 支付宝到账 (-933727923)
10-06 10:52:08 [SUCCESS] nonebot | ONEBOT V11 3544086963 | [message]: {'time': 1665024727, 'self_id': 3544086963, 'post_type': 'message', 'group_id': 805902339, 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Broken_Deer', 'role': 'owner', 'sex': 'unknown', 'title': '', 'user_id': 3472054691}, 'anonymous': None, 'user_id': 3472054691, 'message_seq': 1269, 'message_type': 'group', 'sub_type': 'normal', 'message_id': -933727923, 'raw_message': '支付宝
到账', 'font': 0, 'message': [{'type': 'text', 'data': {'text': '支付宝到账'}}]}
10-06 10:52:08 [WARNING] nonebot | Error while parsing command for event
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 194, in handle_event
    await handle_event(self, event)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 307, in handle_event
    TrieRule.get_value(bot, event, state)
  File "D:\Python\lib\site-packages\nonebot\rule.py", line 189, in get_value
    message = event.get_message()
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 49, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
10-06 10:52:08 [ERROR] nonebot | Rule check failed for <Matcher from nonebot_plugin_gocqhttp.plugin, type=message, priority=1, temp=False>.
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    if not await Matcher.check_perm(
  File "D:\Python\lib\site-packages\nonebot\matcher.py", line 311, in check_perm
    return event_type == (cls.type or event_type) and await cls.permission(
  File "D:\Python\lib\site-packages\nonebot\permission.py", line 111, in __call__
    results = await asyncio.gather(
  File "D:\Python\lib\site-packages\nonebot\permission.py", line 31, in _run_coro_with_catch
    return await coro
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 76, in __call__
    return await self.call(**values)
  File "D:\Python\lib\site-packages\nonebot\permission.py", line 210, in __call__
    f"{bot.adapter.get_name().split(maxsplit=1)[0].lower()}:{event.get_user_id()}"
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 53, in get_user_id
    raise ValueError("Event has no context!")
ValueError: Event has no context!
10-06 10:52:08 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.nonebot_plugin_cute_message, type=message, priority=30, temp=False>.
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 144, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "D:\Python\lib\site-packages\nonebot\matcher.py", line 340, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "D:\Python\lib\site-packages\nonebot\rule.py", line 144, in __call__
    results = await asyncio.gather(
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 76, in __call__
    return await self.call(**values)
  File "E:\Desktop\bot\smart-driver\.\src\plugins\nonebot_plugin_cute_message\__init__.py", line 40, in _can_reply
    input_message = event.get_plaintext()
  File "D:\Python\lib\site-packages\nonebot\adapters\_event.py", line 124, in get_plaintext
    return self.get_message().extract_plain_text()
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 49, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
10-06 10:52:09 [ERROR] nonebot | Rule check failed for <Matcher from src.plugins.nonebot_plugin_jrrp, type=message, priority=60, temp=False>.
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\Python\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\Python\lib\site-packages\nonebot\__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "D:\Python\lib\site-packages\nonebot\drivers\fastapi.py", line 232, in run
    uvicorn.run(
  File "D:\Python\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "D:\Python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "D:\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "D:\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "D:\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Python\lib\site-packages\nonebot\message.py", line 144, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "D:\Python\lib\site-packages\nonebot\matcher.py", line 340, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "D:\Python\lib\site-packages\nonebot\rule.py", line 144, in __call__
    results = await asyncio.gather(
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 73, in __call__
    values = await self.solve(**kwargs)
  File "D:\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 180, in solve
    value = await field_info._solve(**params)
  File "D:\Python\lib\site-packages\nonebot\params.py", line 158, in _solve
    solved = await task
  File "D:\Python\lib\site-packages\nonebot\params.py", line 266, in _event_plain_text
    return event.get_plaintext()
  File "D:\Python\lib\site-packages\nonebot\adapters\_event.py", line 124, in get_plaintext
    return self.get_message().extract_plain_text()
  File "D:\Python\lib\site-packages\nonebot\adapters\onebot\v11\event.py", line 49, in get_message
    raise ValueError("Event has no message!")
ValueError: Event has no message!
```

**Comment by A-kirami** [comment]
请尝试将nb升级为最新版本

**Comment by Broken-Deer** [comment]
不知道咋捣鼓的，也没升级，结果能用了。。。
